<a href="https://colab.research.google.com/github/AYUshJaiswal454/Harsh-Sir-Classes/blob/main/lecture_4(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 3, 9, 0, 2])
print(a)


[1 3 9 0 2]


In [ ]:
a = np.array([1, 3, 9, 0, 'hello'])
print(a)

['1' '3' '9' '0' 'hello']


numpy array return same type of data

In [ ]:
# Question

np_arr = np.array([3,3,4,3.3,'hello',False])
print(bool(np_arr[-1]))






True


In [ ]:
a = 0
print(bool(a))

False


In [ ]:
a = '0'
print(bool(a))

True


in previous case 0 is behave as string and string has a value       and we know bool of value is true


In [ ]:
a = np.zeros((2, 3, 4),dtype=int)
print(a)

print(type(a[0][0][0]))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.int64'>


In [ ]:
a = np.ones((2, 3, 4),dtype=int)
print(a)


print(type(a[0][0][0]))


[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
<class 'numpy.int64'>


In [ ]:
a = np.empty((2, 3, 4),dtype=int)
print(a)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [ ]:
# full
a = np.full(4,5,dtype=int)
print(a)

[5 5 5 5]


In [ ]:
# arange
a = np.arange(0,9,2,dtype=int)
print(a)

[0 2 4 6 8]


In [ ]:
# linspace
a = np.linspace(3, 12, 4, dtype=int)
print(a)

[ 3  6  9 12]


In [ ]:
# Shape and Size of 1-D array
a = np.arange(0,9,2,dtype=int)
print(a.shape)
print(a.size)

(5,)
5


In [ ]:
# Shape and Size of 2-D array
a = np.ones((2, 3),dtype=int)
print(a.shape)
print(a.size)

(2, 3)
6


In [ ]:
# Random Number Generation

a = np.random.randint(0,9,2)
print(a)

[0 1]


In [ ]:
a = np.random.choice([1,7,4],2)
print(a)

[1 7]


In [ ]:

# Broadcasting

a = np.array([1,2,3,4])

b = np.array([9,3,4,6])
print(a*2)
print(a+b)
print(a*b)
print(a/b)
print((2*a)+b)

[2 4 6 8]
[10  5  7 10]
[ 9  6 12 24]
[0.11111111 0.66666667 0.75       0.66666667]
[11  7 10 14]


In [ ]:
# Array into Matrix

a = np.random.randint(2, 15, 6)
print(a)

print(a.reshape(2,3))


print(a.reshape(3,2))


[ 9  3  4  7  9 14]
[[ 9  3  4]
 [ 7  9 14]]
[[ 9  3]
 [ 4  7]
 [ 9 14]]


In [ ]:
# Transpose

a = np.random.randint(2, 15, 6)
print(a)
b = a.reshape(2,3)
print(b)
print(b.transpose())

[ 3 12  5  9  2  2]
[[ 3 12  5]
 [ 9  2  2]]
[[ 3  9]
 [12  2]
 [ 5  2]]


In [ ]:
# Concatenate in 1-D array

a = np.random.randint(2, 15, 6)
print(a)
b = np.random.randint(2, 15, 6)
print(b)


print(np.concatenate((a,b)))




[8 5 5 4 5 3]
[ 7 10  2 12  3 10]
[ 8  5  5  4  5  3  7 10  2 12  3 10]


In [ ]:
# Concatenate in 2-D array



In [ ]:
a = np.random.randint(2, 15, 6)
print(a)
b = np.random.randint(1, 15, 6)
print(b)

c = np.where(b > 2, b, a)
print(c)

[ 3  6  9  2  3 11]
[13  1  9  2  5  8]
[13  6  9  2  5  8]


In [ ]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.sort(a))
b = np.random.randint(2, 15, 6)
print(b)
print(np.sort(b))

[ 9 14  7 12 11 14]
[ 7  9 11 12 14 14]
[ 9  6 13 11 11  9]
[ 6  9  9 11 11 13]


In [ ]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.sum(a))
b = np.random.randint(2, 15, 6)
print(b)
print(np.sum(b))

[10  3  2 11  3 11]
40
[ 3  3 13 11 10  3]


In [ ]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.mean(a))
b = np.random.randint(2, 15, 6)
print(b)
print(np.mean(b))

[11  6  4 13  5 10]
8.166666666666666
[14 11  5  6 12 14]
10.333333333333334


In [ ]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.std(a))
b = np.random.randint(2, 15, 6)
print(b)
print(np.std(b))

[12  9 14 13  7  3]
3.815174380753199
[7 9 3 9 8 3]
2.565800719723442


In [ ]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.min(a))

b = np.random.randint(2, 15, 6)
print(b)
print(np.max(b))

[ 5 13  7  2  7 12]
2
[12 12  4 11  2 13]
13


In [ ]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.unique(a))
b = np.random.randint(2, 15, 6)
print(b)
print(np.unique(b))

[14 14  7  7  3  3]
[ 3  7 14]
[ 4 12  5 12  6  5]
[ 4  5  6 12]


In [ ]:
a = np.random.randint(2, 15, 6)
print(a)
c = a.reshape(2, 3)




b = np.random.randint(2, 15, 6)
print(b)
d = b.reshape(3, 2)

print(np.matmul(c,d))



In [ ]:
scores = []

days = []

for i in range(0,7,1) :
  runs = input(np.array(()))








# balls = input(np.array())
# print(balls)


In [ ]:
scores = input().split()
print(scores)


scores = [int(x) for x in scores]
print(scores)