<a href="https://colab.research.google.com/github/AYUshJaiswal454/Harsh-Sir-Classes/blob/main/Lecture_5(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np;

In [ ]:
# Question
a = np.random.randint(0,90,25)
print(a)

b = a.reshape(5,5)
print(b)




# mean
print(np.mean(b, 1))

print(np.mean(b, 0))



# replace even no

newB = np.where(b%2 == 0,b,-1)
print(newB)

# sort row ad column

sorted_row = print(np.sort(b, axis=0))
sorted_column = print(np.sort(b, axis=1))

# sum row and column wise

sum_row = print(np.sum(b, axis=0))
sum_column = print(np.sum(b, axis=1))


# count negative number in column

count_col = print(np.count_nonzero(newB < 0, axis = 0))

count










[10 41  4 11 60 72 35 88 63 85 39 13 56 88  8 55 35  2 82 86 31 29 83 65
 64]
[[10 41  4 11 60]
 [72 35 88 63 85]
 [39 13 56 88  8]
 [55 35  2 82 86]
 [31 29 83 65 64]]
[25.2 68.6 40.8 52.  54.4]
[41.4 30.6 46.6 61.8 60.6]
[[10 -1  4 -1 60]
 [72 -1 88 -1 -1]
 [-1 -1 56 88  8]
 [-1 -1  2 82 86]
 [-1 -1 -1 -1 64]]
[[10 13  2 11  8]
 [31 29  4 63 60]
 [39 35 56 65 64]
 [55 35 83 82 85]
 [72 41 88 88 86]]
[[ 4 10 11 41 60]
 [35 63 72 85 88]
 [ 8 13 39 56 88]
 [ 2 35 55 82 86]
 [29 31 64 65 83]]
[207 153 233 309 303]
[126 343 204 260 272]
[3 5 1 3 1]


In [ ]:
a = np.random.randint(20,80,25)
print(a)


b = np.random.randint(20,80,25)
print(b)

stock = a.reshape(5,5)
print(stock)
demand = b.reshape(5,5)
print(demand)

# remaining stocks

remaining_stock = stock - demand
print(remaining_stock)



# Negative -> Zeros

zrStocks = np.where(remaining_stock < 0,0,remaining_stock)
print(zrStocks)



# total shortage

total_shortage = np.sum(np.where(remaining_stock < 0,remaining_stock * -1, 0))


# product with zero stock

product_shortage = np.sum(np.where(remaining_stock < 0, 1, 0), axis = 0)



# sort each row basde on remaining stocks

sorted = np.sort(zrStocks, axis = 1)




[55 58 38 47 52 77 68 41 42 69 71 29 55 23 21 36 30 48 54 26 58 39 74 71
 51]
[54 68 50 21 54 64 27 22 52 68 63 24 63 23 65 38 67 29 32 22 24 46 37 43
 61]
[[55 58 38 47 52]
 [77 68 41 42 69]
 [71 29 55 23 21]
 [36 30 48 54 26]
 [58 39 74 71 51]]
[[54 68 50 21 54]
 [64 27 22 52 68]
 [63 24 63 23 65]
 [38 67 29 32 22]
 [24 46 37 43 61]]
[[  1 -10 -12  26  -2]
 [ 13  41  19 -10   1]
 [  8   5  -8   0 -44]
 [ -2 -37  19  22   4]
 [ 34  -7  37  28 -10]]
[[ 1  0  0 26  0]
 [13 41 19  0  1]
 [ 8  5  0  0  0]
 [ 0  0 19 22  4]
 [34  0 37 28  0]]
